default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-39591_development   #アプリによって変更

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-39591_test            #アプリによって変更

production:
  <<: *default
  adapter: mysql2
  database: furima-39591_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock